### ISSUE TITLE
Complete the first task and submit as directed.

### ISSUE THREAD

**Issue by localhost-8000** [nitawebdevs/NITA_WebDevs_Hacktoberfest2021#1]

**Comment by mdArshad10** [comment]
Please assign this issue to me

**Comment by Ankur-9598** [comment]
Hi @HimangsKalita sure. Work on it. It is open for all

**Comment by Ankur-9598** [comment]
> I would like to work on it though it might take time, I am new to this type of project

Hi @HimangsKalita, start working. It is open for all.

**Comment by Ankur-9598** [comment]
> Please assign this issue to me

Hi @mdArshad10 sure..start working

**Comment by Ankur-9598** [comment]
> hey ..! Please assign it to me

@Sorabh3127 start working
